# Generated by Django 4.2.5 on 2023-09-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urbanparktreesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesTreesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(choices=[('Plantation', 'Plantation'), ('Natural', 'Natural')], default='Plantation', max_length=30)),
                ('tree_code', models.CharField(max_length=200)),
                ('plantation_year', models.IntegerField()),
                ('girth_cm', models.FloatField()),
                ('average_height', models.FloatField()),
                ('vol_meter_cube', models.FloatField()),
                ('carbon_content_analysis', models.TextField()),
                ('land', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.landinformation')),
                ('tree_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.treespecies')),
            ],
        ),
    ]
