# Generated by Django 4.2.5 on 2023-09-23 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accountinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('local_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.locallevel')),
            ],
        ),
        migrations.AddField(
            model_name='locallevel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.province'),
        ),
        migrations.CreateModel(
            name='LandInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitta_number', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('gps_longitude', models.FloatField()),
                ('gps_latitude', models.FloatField()),
                ('is_greater_than_10Ha', models.BooleanField(default=False)),
                ('local_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.locallevel')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ward')),
            ],
        ),
    ]
