# Generated by Django 4.2.5 on 2023-09-24 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_locallevel_province_ward_locallevel_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='STRSForestInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_code', models.CharField(max_length=200)),
                ('plantation_year', models.IntegerField()),
                ('girth_cm', models.FloatField()),
                ('average_height', models.FloatField()),
                ('tree_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.treespecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
