# Generated by Django 4.2.5 on 2023-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_treespecies_strsforestinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='strsforestinformation',
            name='tree_type',
            field=models.CharField(choices=[('Plantation', 'Plantation'), ('Natural', 'Natural')], default='Plantation', max_length=30),
        ),
    ]
