# Generated by Django 4.2.5 on 2023-09-26 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_strsforestinformation_tree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinformation',
            name='local_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_level', to='main.locallevel'),
        ),
        migrations.AlterField(
            model_name='landinformation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='main.province'),
        ),
        migrations.AlterField(
            model_name='landinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landinformation',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='main.ward'),
        ),
        migrations.AlterField(
            model_name='locallevel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_levels', to='main.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='local_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='main.locallevel'),
        ),
    ]
