# Generated by Django 4.2.5 on 2023-09-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_landinformation_local_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locallevel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_level', to='main.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='local_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='main.locallevel'),
        ),
    ]
